# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import basic_types_pb2 as basic__types__pb2


class RemoteMLStub(object):
    """RemoteML service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Train = channel.unary_unary(
                '/RemoteMLPackage.RemoteML/Train',
                request_serializer=basic__types__pb2.NDArray.SerializeToString,
                response_deserializer=basic__types__pb2.Empty.FromString,
                )
        self.FaultIndicator = channel.unary_unary(
                '/RemoteMLPackage.RemoteML/FaultIndicator',
                request_serializer=basic__types__pb2.NDArray.SerializeToString,
                response_deserializer=basic__types__pb2.Float.FromString,
                )


class RemoteMLServicer(object):
    """RemoteML service
    """

    def Train(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FaultIndicator(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RemoteMLServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Train': grpc.unary_unary_rpc_method_handler(
                    servicer.Train,
                    request_deserializer=basic__types__pb2.NDArray.FromString,
                    response_serializer=basic__types__pb2.Empty.SerializeToString,
            ),
            'FaultIndicator': grpc.unary_unary_rpc_method_handler(
                    servicer.FaultIndicator,
                    request_deserializer=basic__types__pb2.NDArray.FromString,
                    response_serializer=basic__types__pb2.Float.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'RemoteMLPackage.RemoteML', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RemoteML(object):
    """RemoteML service
    """

    @staticmethod
    def Train(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/RemoteMLPackage.RemoteML/Train',
            basic__types__pb2.NDArray.SerializeToString,
            basic__types__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FaultIndicator(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/RemoteMLPackage.RemoteML/FaultIndicator',
            basic__types__pb2.NDArray.SerializeToString,
            basic__types__pb2.Float.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
