# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: remote_ml.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import basic_types_pb2 as basic__types__pb2

from basic_types_pb2 import *

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fremote_ml.proto\x12\x0fRemoteMLPackage\x1a\x11\x62\x61sic_types.proto2M\n\x08RemoteML\x12\x1b\n\x05Train\x12\x08.NDArray\x1a\x06.Empty\"\x00\x12$\n\x0e\x46\x61ultIndicator\x12\x08.NDArray\x1a\x06.Float\"\x00P\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'remote_ml_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REMOTEML._serialized_start=55
  _REMOTEML._serialized_end=132
# @@protoc_insertion_point(module_scope)
